# Generated by Django 5.2.6 on 2026-02-22 15:47

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estyecomapp', '0001_initial'),
        ('users', '0002_alter_profile_options_profile_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutGiftFinder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default="If you need gift ideas for anybody – and we mean ANYBODY – in your life, you've come to the right place.", max_length=200)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='Gift', max_length=50)),
                ('button_text_more', models.CharField(default='More', max_length=20)),
                ('button_text_less', models.CharField(default='Less', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FashionDiscover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='fashion_discover/')),
                ('url', models.CharField(max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='FashionPromoCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='fashion_promo/')),
                ('button_text', models.CharField(default='Shop now', max_length=50)),
                ('button_url', models.CharField(max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='FashionShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('display_name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='fashion_shops/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='fashion_shops/covers/')),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FashionTrending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='fashion_trending/')),
                ('button_text', models.CharField(default='Try it out', max_length=50)),
                ('button_url', models.CharField(max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GiftCardBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('button_text', models.CharField(default='Pick a design', max_length=50)),
                ('button_url', models.CharField(default='/gift-cards', max_length=500)),
                ('gradient_from', models.CharField(default='from-yellow-300', max_length=50)),
                ('gradient_via', models.CharField(default='via-orange-400', max_length=50)),
                ('gradient_to', models.CharField(default='to-green-500', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', '-created'],
            },
        ),
        migrations.CreateModel(
            name='GiftCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('interest_tag', models.CharField(blank=True, max_length=100, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='GiftCollectionProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_title', models.CharField(blank=True, max_length=255, null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', '-created'],
            },
        ),
        migrations.CreateModel(
            name='GiftGridItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='gift_grid/')),
                ('size', models.CharField(choices=[('small', 'Small'), ('large', 'Large')], default='small', max_length=10)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='GiftGuideProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etsy_pick', models.BooleanField(default=False, help_text="Marked as Etsy's Pick")),
                ('custom_title', models.CharField(blank=True, help_text='Custom title for display', max_length=255, null=True)),
                ('custom_description', models.TextField(blank=True, help_text='Custom description', null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('shop_name', models.CharField(blank=True, max_length=100, null=True)),
                ('badge_text', models.CharField(blank=True, help_text="e.g., '25% off', 'Free delivery'", max_length=50, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', '-created'],
            },
        ),
        migrations.CreateModel(
            name='GiftGuideSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('section_type', models.CharField(choices=[('best_gift_guides', 'Best Gift Guides'), ('valentines_gifts', "Valentine's Day Gifts"), ('bestselling_gifts', 'Best-Selling Gifts'), ('best_of_valentine', "Best of Valentine's Day"), ('personalized_presents', 'Presents to Personalize')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='gift_sections/')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='gift_sections/backgrounds/')),
                ('guide_links', models.JSONField(blank=True, default=list, help_text="List of guide links in format: {'title': '...', 'url': '...'}", null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gift Guide Section',
                'verbose_name_plural': 'Gift Guide Sections',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='GiftInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GiftOccasion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('date', models.CharField(blank=True, max_length=20, null=True)),
                ('icon', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='GiftPersona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('persona_type', models.CharField(choices=[('collection', 'Collection Persona'), ('guilty_pleasure', 'Guilty Pleasure'), ('zodiac_sign', 'Zodiac Sign'), ('interest', 'Interest'), ('related_idea', 'Related Gift Idea')], default='collection', max_length=50)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='gift_personas/')),
                ('bg_color', models.CharField(blank=True, max_length=50, null=True)),
                ('accent_color', models.CharField(blank=True, max_length=50, null=True)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GiftRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='GiftRecipientItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='gift_recipients/')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='GiftTeaserBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('badge_text', models.CharField(default='✨ New', max_length=50)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', '-created'],
            },
        ),
        migrations.CreateModel(
            name='GiftTeaserFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PopularGiftCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='estyecomapp_created_926418_idx',
        ),
        migrations.RemoveField(
            model_name='product',
            name='dimensions',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weight',
        ),
        migrations.AlterField(
            model_name='brand',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('main', 'Main Category'), ('gift_occasion', 'Gift Occasion'), ('gift_interest', 'Gift Interest'), ('gift_recipient', 'Gift For Everyone'), ('gift_popular', 'Popular Gifts'), ('gifts', 'Gifts'), ('fashion_finds', 'Fashion Finds'), ('home_favourites', 'Home Favourites')], db_index=True, default='main', max_length=50),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=datetime.datetime.now, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='homepagesection',
            name='section_type',
            field=models.CharField(choices=[('picks_inspired', 'Picks Inspired by Shopping'), ('featured_interests', 'Featured Interests'), ('seasonal', 'Special Season'), ('big_deals', "Today's Big Deals"), ('editors_guide', "Editor's Guide"), ('vintage_guide', 'Vintage Guide'), ('banner', 'Banner'), ('gifts', 'Gifts Section'), ('top_100_gifts', 'Top 100 Gifts'), ('fashion_finds', 'Fashion Finds'), ('home_favourites', 'Home Favourites'), ('gift_guides', 'Best Gift Guides'), ('valentines_gifts', "Valentine's Day Gifts"), ('best_of_valentine', "Best of Valentine's Day"), ('bestselling_gifts', 'Best-Selling Gifts'), ('personalized_presents', 'Presents to Personalize'), ('fashion_trending', 'Fashion Trending Now'), ('fashion_promo', 'Fashion Promo Cards'), ('fashion_shops', 'Fashion Shops We Love'), ('fashion_discover', 'Fashion Discover More')], max_length=50),
        ),
        migrations.AlterField(
            model_name='parentcategory',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='parentcategory',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='parentcategory',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='parentcategory',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='available_sizes',
            field=models.ManyToManyField(blank=True, to='estyecomapp.productsize'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estyecomapp.brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_bestseller',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_deal',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_new_arrival',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, to='estyecomapp.tag'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='category',
            field=models.CharField(choices=[('clothing', 'Clothing'), ('shoes', 'Shoes'), ('jewelry', 'Jewelry'), ('home', 'Home & Living'), ('other', 'Other')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['slug', 'is_active'], name='estyecomapp_slug_1bb295_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['slug', 'is_active'], name='estyecomapp_slug_89f57f_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['category_type', 'is_featured'], name='estyecomapp_categor_7b7f9e_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent', 'order'], name='estyecomapp_parent__e22280_idx'),
        ),
        migrations.AddIndex(
            model_name='parentcategory',
            index=models.Index(fields=['slug', 'is_active'], name='estyecomapp_slug_b0d1e0_idx'),
        ),
        migrations.AddIndex(
            model_name='parentcategory',
            index=models.Index(fields=['is_featured', 'order'], name='estyecomapp_is_feat_74614f_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_deal', '-discount_price'], name='estyecomapp_is_deal_31abb6_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_bestseller', '-rating'], name='estyecomapp_is_best_d7500c_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_new_arrival', '-created'], name='estyecomapp_is_new__8ceab5_idx'),
        ),
        migrations.AddIndex(
            model_name='productsize',
            index=models.Index(fields=['category', 'code'], name='estyecomapp_categor_6fcf7b_idx'),
        ),
        migrations.AddField(
            model_name='fashionshop',
            name='featured_products',
            field=models.ManyToManyField(blank=True, related_name='fashion_shops', to='estyecomapp.product'),
        ),
        migrations.AddField(
            model_name='giftcollectionproduct',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_products', to='estyecomapp.giftcollection'),
        ),
        migrations.AddField(
            model_name='giftcollectionproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gift_collections', to='estyecomapp.product'),
        ),
        migrations.AddField(
            model_name='giftgriditem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gift_grid_items', to='estyecomapp.product'),
        ),
        migrations.AddField(
            model_name='giftguideproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gift_guide_entries', to='estyecomapp.product'),
        ),
        migrations.AddField(
            model_name='giftguidesection',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='gift_guide_sections', to='estyecomapp.category'),
        ),
        migrations.AddField(
            model_name='giftguidesection',
            name='featured_products',
            field=models.ManyToManyField(blank=True, related_name='gift_guide_sections', to='estyecomapp.product'),
        ),
        migrations.AddField(
            model_name='giftguideproduct',
            name='gift_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gift_products', to='estyecomapp.giftguidesection'),
        ),
        migrations.AddField(
            model_name='giftcollection',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='estyecomapp.giftpersona'),
        ),
        migrations.AddField(
            model_name='giftrecipientitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipient_items', to='estyecomapp.product'),
        ),
        migrations.AddField(
            model_name='giftrecipientitem',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='estyecomapp.giftrecipient'),
        ),
        migrations.AddField(
            model_name='giftteaserfeature',
            name='banner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='estyecomapp.giftteaserbanner'),
        ),
        migrations.AlterUniqueTogether(
            name='giftcollectionproduct',
            unique_together={('collection', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='giftguideproduct',
            unique_together={('gift_section', 'product')},
        ),
    ]
