# Generated by Django 5.2.6 on 2026-03-08 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estyecomapp', '0002_aboutgiftfinder_fashiondiscover_fashionpromocard_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessorySubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True, help_text='Cover image URL for category card')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Accessory Sub-Category',
                'verbose_name_plural': 'Accessory Sub-Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('main', 'Main Category'), ('gift_occasion', 'Gift Occasion'), ('gift_interest', 'Gift Interest'), ('gift_recipient', 'Gift For Everyone'), ('gift_popular', 'Popular Gifts'), ('gifts', 'Gifts'), ('fashion_finds', 'Fashion Finds'), ('home_favourites', 'Home Favourites'), ('accessories', 'Accessories')], db_index=True, default='main', max_length=50),
        ),
        migrations.CreateModel(
            name='AccessoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, help_text='Original / RRP price before discount', max_digits=10, null=True)),
                ('discount_pct', models.PositiveSmallIntegerField(default=0, help_text='Discount percentage e.g. 60')),
                ('image_url', models.URLField()),
                ('shop_name', models.CharField(blank=True, max_length=120)),
                ('star_rating', models.DecimalField(decimal_places=1, default=0.0, help_text='0.0 – 5.0', max_digits=3)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('is_star_seller', models.BooleanField(default=False)),
                ('is_ad', models.BooleanField(default=False, help_text='Sponsored / Ad listing')),
                ('has_free_delivery', models.BooleanField(default=False)),
                ('is_on_sale', models.BooleanField(default=False)),
                ('badge_label', models.CharField(blank=True, help_text="e.g. 'SHIPS FROM USA', 'FAST SHIPPING'", max_length=60)),
                ('shop_country', models.CharField(default='Anywhere', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sub_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='estyecomapp.accessorysubcategory')),
            ],
            options={
                'ordering': ['-review_count'],
            },
        ),
    ]
