# Generated by Django 5.2.6 on 2026-03-08 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estyecomapp', '0003_accessorysubcategory_alter_category_category_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessoryitem',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
