# Generated by Django 5.2.6 on 2026-03-08 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estyecomapp', '0004_alter_accessoryitem_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True, help_text='Cover image URL for category card')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Art Sub-Category',
                'verbose_name_plural': 'Art Sub-Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ArtItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, help_text='Original / RRP price before discount', max_digits=10, null=True)),
                ('discount_pct', models.PositiveSmallIntegerField(default=0, help_text='Discount percentage e.g. 25')),
                ('image_url', models.URLField()),
                ('shop_name', models.CharField(blank=True, max_length=120)),
                ('star_rating', models.DecimalField(decimal_places=1, default=0.0, help_text='0.0 – 5.0', max_digits=3)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('is_star_seller', models.BooleanField(default=False)),
                ('is_ad', models.BooleanField(default=False)),
                ('has_free_delivery', models.BooleanField(default=False)),
                ('is_on_sale', models.BooleanField(default=False)),
                ('is_digital_download', models.BooleanField(default=False, help_text='Digital download product')),
                ('badge_label', models.CharField(blank=True, max_length=60)),
                ('shop_country', models.CharField(default='Anywhere', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sub_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='estyecomapp.artsubcategory')),
            ],
            options={
                'ordering': ['-review_count'],
            },
        ),
    ]
